# Generated by Django 5.1.2 on 2024-11-02 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('addres', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.CharField(max_length=50, unique=True)),
                ('e_addres', models.CharField(max_length=150)),
                ('e_cpf', models.CharField(max_length=11, unique=True)),
                ('e_rg', models.CharField(max_length=9, unique=True)),
                ('e_phone', models.CharField(max_length=11, unique=True)),
                ('e_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('1', 'Pix'), ('2', 'Débito'), ('3', 'Crédito'), ('4', 'Dinheiro'), ('5', 'Nulo')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status_p', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_o', models.CharField(choices=[('1', 'Iniciado'), ('2', 'Em andamento'), ('3', 'Finalizado'), ('4', 'Cancelado')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('o_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.clients')),
                ('o_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.payments')),
                ('o_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.products')),
                ('s_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficina.services')),
            ],
        ),
    ]
